# Generated by Django 5.2.1 on 2025-05-27 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("characters", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="character",
            name="image",
            field=models.URLField(max_length=255),
        ),
    ]
